services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    volumes:
      - ./:/flask
    command: ["python3", "main.py"]
  sqlexpress:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlexpress
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: always

volumes:
  sql_data: